-- 코드를 입력하세요
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) as SCORE
from REST_INFO
JOIN REST_REVIEW on REST_INFO.REST_ID = REST_REVIEW.REST_ID
GROUP BY REST_NAME
HAVING address  Like '서울%' 
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;


