-- 코드를 입력하세요
SELECT t1.FLAVOR
FROM FIRST_HALF as t1, ICECREAM_INFO as t2
WHERE t1.TOTAL_ORDER > 3000 AND t2.INGREDIENT_TYPE = 'fruit_based' AND t1.FLAVOR = t2.FLAVOR
GROUP BY t1.FLAVOR
ORDER BY t1.TOTAL_ORDER DESC